FORMAT: 1A
HOST: http://laikapp.herokuapp.com

# Laika API

Laika is an API service to return astronomy information and data. It can be used to obtain information about past and future space missions, astronauts, telescopes in function, newly discovered exoplanets and much more. Everything is returned in a standard JSON format.

## News [/api/v1/news]

### List all news [GET]

+ Response 200 (application/json)

            {
                "news": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
                        "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
                        "img": "",
                        "source": "https://www.nasa.gov",
                        "tags": ["nasa", "spacex", "iss"],
                    }, {
                        "id": 2,
                        "date": "17/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Arrive at Space Station",
                        "content": " The SpaceX Crew Dragon Resilience successfully docked to the International Space Station at 11 p.m. EST Monday, transporting NASA astronauts Michael Hopkins, Victor Glover, Shannon Walker, and Japan Aerospace Exploration Agency (JAXA) astronaut Soichi Noguchi.",
                        "img": "https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw2046a.jpg"
                        "source": "https://www.nasa.gov",
                        "tags": ["nasa", "spacex", "iss"],
                    }, {
                        "id": 3,
                        "date": "17/11/2020",
                        "title": "NASA Highlights Science, New Airlock on Space Station Resupply Mission",
                        "content": "NASA will host a media teleconference at 1 p.m. EST Friday, Nov. 20, to discuss science investigations and a new privately funded airlock launching on SpaceX’s 21st commercial cargo resupply mission for the agency to the International Space Station.",
                        "img": ""
                        "source": "https://www.nasa.gov",
                        "tags": ["nasa"],
                    }
                ]
            }

### Add a new news [POST]

You may add a new news using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

        {
            "date": "21/11/2020",
            "title": "Sea-level monitoring satellite in position for liftoff",
            "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
            "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
            "source": "https://www.esa.int",
            "tags": ["nasa"],
        }

+ Response 201 (application/json)

    + Headers

            Location: /news/4

    + Body

            {
                "id": 4,
                "date": "21/11/2020",
                "title": "Sea-level monitoring satellite in position for liftoff",
                "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
                "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
                "source": "https://www.esa.int",
            }

## Specific News [/api/v1/news/{id}]

### Get a specific news [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "date": "16/11/2020",
            "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
            "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
            "img": "",
            "source": "https://www.nasa.gov",
            "tags": ["nasa"],
        }

### Update a specific news [PUT]

You may update an existing news using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 4,
            "date": "21/11/2020",
            "title": "Sea-level monitoring satellite in position for liftoff",
            "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
            "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
            "source": "https://www.esa.int",
            "tags": ["nasa"],
        }

+ Response 202 (application/json)

    + Headers

            Location: /news/4

    + Body

            {
                "id": 4,
                "date": "21/11/2020",
                "title": "Sea-level monitoring satellite in position for liftoff",
                "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
                "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
                "source": "https://www.esa.int",
            }

### Delete a specific news [DELETE]

You may delete an existing news using this action. It takes a JSON object containing the id of the news to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
            }

## Latest News [/api/v1/news/latest/{size}]

### Get the latest news [GET]

You may get the latest news using this action. You need to specify the number of how many news you want to be returned.

+ Response 200 (application/json)

            {
                "news": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
                        "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
                        "img": "",
                        "source": "https://www.nasa.gov",
                        "tags": ["nasa", "spacex", "iss"],
                    }, {
                        "id": 2,
                        "date": "17/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Arrive at Space Station",
                        "content": " The SpaceX Crew Dragon Resilience successfully docked to the International Space Station at 11 p.m. EST Monday, transporting NASA astronauts Michael Hopkins, Victor Glover, Shannon Walker, and Japan Aerospace Exploration Agency (JAXA) astronaut Soichi Noguchi.",
                        "img": "https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw2046a.jpg"
                        "source": "https://www.nasa.gov",
                        "tags": ["nasa", "spacex", "iss"],
                    }, {
                        "id": 3,
                        "date": "17/11/2020",
                        "title": "NASA Highlights Science, New Airlock on Space Station Resupply Mission",
                        "content": "NASA will host a media teleconference at 1 p.m. EST Friday, Nov. 20, to discuss science investigations and a new privately funded airlock launching on SpaceX’s 21st commercial cargo resupply mission for the agency to the International Space Station.",
                        "img": ""
                        "source": "https://www.nasa.gov",
                        "tags": ["nasa"],
                    }
                ]
            }
            
## Missions [/api/v1/missions]

### List all missions [GET]

+ Response 200 (application/json)

            {
                "missions": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "CREW-1 MISSION",
                        "content": "n Monday, November 16 at 11:01 p.m. EST, 04:01 UTC on November 17, SpaceX’s Dragon autonomously docked with the International Space Station (ISS) after Falcon 9 launched the spacecraft to orbit from historic Launch Complex 39A (LC-39A) at NASA’s Kennedy Space Center in Florida on Sunday, November 15, 2020.",
                        "img": "",
                        "source": "https://www.spacex.com/updates/crew-1-docks-to-iss/index.html",
                        "tags": ["iss", "spacex", "nasa"],
                    }, {
                        "id": 2,
                        "date": "18/12/2019",
                        "title": "Cheops",
                        "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
                        "img": ""
                        "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
                        "tags": ["esa", "exoplanets"],
                    }
                ]
            }

### Add a new missions [POST]

You may add a new mission using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

        {
            "date": "18/12/2019",
            "title": "Cheops",
            "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
            "img": ""
            "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
            "tags": ["esa", "exoplanets"],
        }

+ Response 201 (application/json)

    + Headers

            Location: /missions/2

    + Body

            {
                "date": "18/12/2019",
                "title": "Cheops",
                "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
                "img": ""
                "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
                "tags": ["esa", "exoplanets"],
            }

## Specific Missions [/api/v1/missions/{id}]

### Get a specific mission [GET]

+ Response 200 (application/json)

        {
            "date": "18/12/2019",
            "title": "Cheops",
            "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
            "img": ""
            "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
            "tags": ["esa", "exoplanets"],
        }

### Update a specific mission [PUT]

You may update an existing news using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 2
            "date": "18/12/2019",
            "title": "Cheops",
            "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
            "img": ""
            "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
            "tags": ["esa", "exoplanets"],
        }

+ Response 202 (application/json)

    + Headers

            Location: /missions/2

    + Body

            {
                "id": 2
                "date": "18/12/2019",
                "title": "Cheops",
                "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
                "img": ""
                "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
                "tags": ["esa", "exoplanets"],
            }

### Delete a specific mission [DELETE]

You may delete an existing mission using this action. It takes a JSON object containing the id of the mission to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /missions/4

    + Body

            {
                "id": 4,
            }

## Latest Missions [/api/v1/missions/latest/{size}]

### Get the latest mission [GET]

You may get the latest missions using this action. You need to specify the number of how many missions you want to be returned.

+ Response 200 (application/json)

            {
                "missions": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "CREW-1 MISSION",
                        "content": "n Monday, November 16 at 11:01 p.m. EST, 04:01 UTC on November 17, SpaceX’s Dragon autonomously docked with the International Space Station (ISS) after Falcon 9 launched the spacecraft to orbit from historic Launch Complex 39A (LC-39A) at NASA’s Kennedy Space Center in Florida on Sunday, November 15, 2020.",
                        "img": "",
                        "source": "https://www.spacex.com/updates/crew-1-docks-to-iss/index.html",
                        "tags": ["iss", "spacex", "nasa"],
                    }, {
                        "id": 2,
                        "date": "18/12/2019",
                        "title": "Cheops",
                        "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
                        "img": ""
                        "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
                        "tags": ["esa", "exoplanets"],
                    }
                ]
            }
            
## Astronauts [/api/v1/astronauts]

### List all astronauts [GET]

+ Response 200 (application/json)

            {
                "astronauts": [
                    {
                        "id": 1,
                        "birth": "27/09/1976",
                        "name": "Luca Parmitano",
                        "nationality": "Italy",
                        "img": "",
                        "agency": "ESA",
                    }, {
                        "id": 2,
                        "birth": "19/09/1987",
                        "name": "Kayla Barron",
                        "nationality": "US",
                        "img": "",
                        "agency": "NASA",
                    }
                ]
            }

### Add a new astronaut [POST]

You may add a new astronaut using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

            {
                "birth": "11/01/1975",
                "name": "Robert Hines",
                "nationality": "US",
                "img": "",
                "agency": "NASA",
            }

+ Response 201 (application/json)

    + Headers

            Location: /astroanuts/2

    + Body

            {
                "id": 3,
                "birth": "11/01/1975",
                "name": "Robert Hines",
                "nationality": "US",
                "img": "",
                "agency": "NASA",
            }

## Specific astronauts [/api/v1/astronauts/{id}]

### Get a specific astronaut [GET]

+ Response 200 (application/json)

            {
                "id": 1,
                "birth": "27/09/1976",
                "name": "Luca Parmitano",
                "nationality": "Italy",
                "img": "",
                "agency": "ESA",
            }

### Update a specific astronaut [PUT]

You may update an existing astronaut using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 1,
            "birth": "27/09/1976",
            "name": "Luca Parmitano",
            "nationality": "Italy",
            "img": "",
            "agency": "ESA",
        }

+ Response 202 (application/json)

    + Headers

            Location: /astronauts/1

    + Body

            {
                "id": 1,
                "birth": "27/09/1976",
                "name": "Luca Parmitano",
                "nationality": "Italy",
                "img": "",
                "agency": "ESA",
            }

### Delete a specific astronaut [DELETE]

You may delete an existing astronaut using this action. It takes a JSON object containing the id of the mission to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /astronauts/4

    + Body

            {
                "id": 4,
            }

## Latest astronauts [/api/v1/astronauts/latest/{size}]

### Get the latest astronauts [GET]

You may get the latest astronauts using this action. You need to specify the number of how many astronauts you want to be returned.

+ Response 200 (application/json)

            {
                "astronauts": [
                    {
                        "id": 1,
                        "birth": "27/09/1976",
                        "name": "Luca Parmitano",
                        "nationality": "Italy",
                        "img": "",
                        "agency": "ESA",
                    }, {
                        "id": 2,
                        "birth": "19/09/1987",
                        "name": "Kayla Barron",
                        "nationality": "US",
                        "img": "",
                        "agency": "NASA",
                    }
                ]
            }
            
## Telescopes [/api/v1/telescopes]

### List all telescopes [GET]

+ Response 200 (application/json)

            {
                "telescopes": [
                    {
                        "id": 1,
                        "date": "24/04/1990",
                        "name": "Hubble Space Telescope",
                        "description": "The Hubble Space Telescope (often referred to as HST or Hubble) is a space telescope that was launched into low Earth orbit in 1990 and remains in operation. It was not the first space telescope, but it is one of the largest and most versatile, well known both as a vital research tool and as a public relations boon for astronomy.",
                        "img": [],
                        "source": "https://www.nasa.gov/mission_pages/hubble/main/index.html",
                        "tags": ["nasa", "esa"],
                    }, {
                        "id": 2,
                        "date": "14/09/2013",
                        "name": "Hisaki Satellite",
                        "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
                        "img": []
                        "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
                        "tags": ["jaxa"],
                    }
                ]
            }

### Add a new telescope [POST]

You may add a new telescope using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

            {
                "date": "14/09/2013",
                "name": "Hisaki Satellite",
                "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
                "img": []
                "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
                "tags": ["jaxa"],
            }

+ Response 201 (application/json)

    + Headers

            Location: /telescopes/2

    + Body

            {
                "id": 2,
                "date": "14/09/2013",
                "name": "Hisaki Satellite",
                "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
                "img": []
                "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
                "tags": ["jaxa"],
            }

## Specific telescope [/api/v1/telescopes/{id}]

### Get a specific telescope [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "date": "14/09/2013",
            "name": "Hisaki Satellite",
            "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
            "img": []
            "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
            "tags": ["jaxa"],
        }

### Update a specific telescope [PUT]

You may update an existing telescope using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 2,
            "date": "14/09/2013",
            "name": "Hisaki Satellite",
            "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
            "img": []
            "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
            "tags": ["jaxa"]
        }

+ Response 202 (application/json)

    + Headers

            Location: /telescopes/2

    + Body

            {
                "id": 2,
                "date": "14/09/2013",
                "name": "Hisaki Satellite",
                "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
                "img": []
                "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
                "tags": ["jaxa"]
            }

### Delete a specific telescope [DELETE]

You may delete an existing telescope using this action. It takes a JSON object containing the id of the telescope to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /telescopes/4

    + Body

            {
                "id": 4,
            }

## Latest telescopes [/api/v1/telescopes/latest/{size}]

### Get the latest telescopes [GET]

You may get the latest telescopes using this action. You need to specify the number of how many telescopes you want to be returned.

+ Response 200 (application/json)

            {
                "telescopes": [
                    {
                        "id": 1,
                        "date": "24/04/1990",
                        "name": "Hubble Space Telescope",
                        "description": "The Hubble Space Telescope (often referred to as HST or Hubble) is a space telescope that was launched into low Earth orbit in 1990 and remains in operation. It was not the first space telescope, but it is one of the largest and most versatile, well known both as a vital research tool and as a public relations boon for astronomy.",
                        "img": [],
                        "source": "https://www.nasa.gov/mission_pages/hubble/main/index.html",
                        "tags": ["nasa", "esa"]
                    }, {
                        "id": 2,
                        "date": "14/09/2013",
                        "name": "Hisaki Satellite",
                        "description": "Hisaki, also known as the Spectroscopic Planet Observatory for Recognition of Interaction of Atmosphere (SPRINT-A) is a Japanese ultraviolet astronomy satellite operated by the Japan Aerospace Exploration Agency (JAXA). The first mission of the Small Scientific Satellite programme,[2] it was launched in September 2013 on the maiden flight of the Epsilon rocket. ",
                        "img": []
                        "source": "https://www.jaxa.jp/projects/sat/sprint_a/",
                        "tags": ["jaxa"]
                    }
                ]
            }
            
## Exoplanets [/api/v1/exoplanets]

### List all exoplanets [GET]

+ Response 200 (application/json)

            {
                "exoplanets": [
                    {
                        "id": 1,
                        "date": "21/10/2013",
                        "name": "WASP-76b",
                        "description": "WASP-76b is a hot Jupiter exoplanet discovered during 2013 that can be found in the constellation Pisces. It orbits a F-type star BD+01 316 (WASP-76) and has a size 0.92 that of Jupiter's mass.",
                        "img": "",
                        "source": "https://en.wikipedia.org/wiki/WASP-76b",
                        "tags": ["nasa"]
                    }, {
                        "id": 2,
                        "date": "15/04/2020",
                        "name": "Kepler-1649c",
                        "description": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
                        "img": []
                        "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
                        "tags": ["kepler"]
                    }
                ]
            }

### Add a new exoplanet [POST]

You may add a newly discovered exoplanet using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

            {
                "id": 2,
                "date": "15/04/2020",
                "name": "Kepler-1649c",
                "description": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
                "img": []
                "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
                "tags": ["kepler"]
            }

+ Response 201 (application/json)

    + Headers

            Location: /exoplanets/2

    + Body

            {
                "id": 2,
                "date": "15/04/2020",
                "name": "Kepler-1649c",
                "description": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
                "img": []
                "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
                "tags": ["kepler"],
            }

## Specific exoplanet [/api/v1/exoplanets/{id}]

### Get a specific exoplanet [GET]

+ Response 200 (application/json)

        {
            "id": 2,
            "date": "15/04/2020",
            "name": "Kepler-1649c",
            "description": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
            "img": []
            "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
            "tags": ["kepler"],
        }

### Update a specific exoplanet [PUT]

You may update an existing exoplanet using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 2,
            "date": "15/04/2020",
            "nam": "Kepler-1649c",
            "description": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
            "img": []
            "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
            "tags": ["kepler"],
        }

+ Response 202 (application/json)

    + Headers

            Location: /exoplanets/2

    + Body

            {
                "id": 2,
                "date": "15/04/2020",
                "name": "Kepler-1649c",
                "description": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
                "img": []
                "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
                "tags": ["kepler"],
            }

### Delete a specific exoplanet [DELETE]

You may delete an existing exoplanet using this action. It takes a JSON object containing the id of the telescope to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /exoplanets/4

    + Body

            {
                "id": 4,
            }

## Latest exoplanets [/api/v1/exoplanets/latest/{size}]

### Get the latest exoplanets [GET]

You may get the latest exoplanets using this action. You need to specify the number of how many exoplanets you want to be returned.

+ Response 200 (application/json)

            {
                "exoplanets": [
                    {
                        "id": 1,
                        "discovery_date": "21/10/2013",
                        "name": "WASP-76b",
                        "description": "WASP-76b is a hot Jupiter exoplanet discovered during 2013 that can be found in the constellation Pisces. It orbits a F-type star BD+01 316 (WASP-76) and has a size 0.92 that of Jupiter's mass.",
                        "img": "",
                        "source": "https://en.wikipedia.org/wiki/WASP-76b",
                        "tags": ["nasa"],
                    }, {
                        "id": 2,
                        "date": "15/04/2020",
                        "name": "Kepler-1649c",
                        "content": "Kepler-1649c is an exoplanet orbiting the M-type main sequence red dwarf star Kepler-1649, about 300 light-years from Earth, nằm trong chòm sao Thiên Nga.",
                        "img": []
                        "source": "https://en.wikipedia.org/wiki/Kepler-1649c",
                        "tags": ["kepler"],
                    }
                ]
            }
            
## Creating and deleting user accounts [/api/v1/signup]

### Sign up [POST]

You may sign up by providing a username and password. It takes a JSON object containing the necessary information.

+ Request (application/json)

            {
                "username": "user1",
                "password": "password",
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
            }
            
### Delete an account [DELETE]

You may delete your account if you're signed in.

+ Request (application/json)

            {
                "token": 2
            }

+ Response 200 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
            }
            
## Signing in [/api/v1/signin]
            
### Sign in [POST]

You may sign in to an existing user account by providing a username and password.

+ Request (application/json)

            {
                "username": "user2",
                "password": "password",
            }

+ Response 200 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
                "token": 2,
                "img": "",
                "saved_articles": [],
                "followed_missions": [],
            }
            
## Saved News [/api/v1/save]
            
### Save a specific article [POST]

If you're signed into your account, you may save an article to then read it later.

+ Request (application/json)

            {
                "token": 2,
                "article_id": 3,
            }

+ Response 202 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
            }

### Delete a specific article [DELETE]

If you're signed into your account, you may delete an article you saved previously.

+ Request (application/json)

            {
                "token": 2,
                "article_id": 3,
            }

+ Response 202 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
            }

## Followed Missions [/api/v1/follow]
            
### Follow a specific mission [POST]

If you're signed into your account, you may follow a specific mission to receive updates of it by name.

+ Request (application/json)

            {
                "token": 2,
                "mission_id": 3,
            }

+ Response 202 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
            }

### Unfollow a specific mission [DELETE]

If you're signed into your account, you unfollow a mission you followed earlier.

+ Request (application/json)

            {
                "token": 2,
                "mission_id": 3,
            }

+ Response 202 (application/json)

    + Headers

            Location: /users/2

    + Body

            {
            }