FORMAT: 1A
HOST: http://laikapp.herokuapp.com

# Laika API

Laika is an API service to return astronomy information and data. It can be used to obtain information about past and future space missions, astronauts, telescopes in function, newly discovered exoplanets and much more. Everything is returned in a standard JSON format.

## News [/api/v1/news]

### List all news [GET]

+ Response 201 (application/json)

            
            [
                {
                    "tags":["nasa","spacex"],
                    "_id":"5fd7a2e7f401d8460e80f3b4",
                    "date":"2020-12-14T17:37:43.558Z",
                    "title":"SXM-7 Mission",
                    "title_lowcase":"sxm-7 mission",
                    "content":"On Sunday, December 13 at 12:30 p.m. EST, Falcon 9 launched the SXM-7 mission from Space Launch Complex 40 (SLC-40) at Cape Canaveral Space Force Station, Florida",
                    "img_path":"https://www.nasaspaceflight.com/wp-content/uploads/2020/12/SXM-7-Falcon-9-B1051-LC-40-vertical-121020-SpaceX-1-scaled.jpg",
                    "source_url":"www.spacex.com",
                    "__v":0
                }, 
                {
                    "tags":["nasa","spacex"],
                    "_id":"5fd889565bd2a2ea724e443d",
                    "date":"2020-12-13T17:37:43.558Z",
                    "title":"NASA, ESA Choose Astronauts for SpaceX Crew-3 Mission to Space Station",
                    "title_lowcase":"nasa, esa choose astronauts for spacex crew-3 mission to space station",
                    "content":"NASA and ESA (European Space Agency) have selected three astronauts to serve as crew members for NASA’s SpaceX Crew-3 mission to the International Space Station, which is expected to launch in the fall of 2021.",
                    "img_path":"https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/crew-3_composite.png",
                    "source_url":"www.nasa.gov",
                    "__v":0
                }
            ]
            

### Add a new news [POST]

You may add a new news using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

    + Headers
    
            X-access-token: token
    
    + Body

            {
                "tags":"nasa,spacex",
                "date":"2020-12-13T17:37:43.558Z",
                "title":"NASA, ESA Choose Astronauts for SpaceX Crew-3 Mission to Space Station",
                "content":"NASA and ESA (European Space Agency) have selected three astronauts to serve as crew members for NASA’s SpaceX Crew-3 mission to the International Space Station, which is expected to launch in the fall of 2021.",
                "img_path":"https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/crew-3_composite.png",
                "source_url":"www.nasa.gov",
            }

+ Response 201 (application/json)

    + Headers

            Location: /news/4

## Specific News [/api/v1/news/{id}]

### Get a specific news [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "date": "16/11/2020",
            "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
            "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
            "img": "",
            "source": "https://www.nasa.gov",
            "tags": ["nasa"],
        }

### Update a specific news [PUT]

You may update an existing news using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

    + Headers
    
            X-access-token: token
    
    + Body

            {
                "tags":"nasa,spacex",
                "date":"2020-12-13T17:37:43.558Z",
                "title":"NASA, ESA Choose Astronauts for SpaceX Crew-3 Mission to Space Station",
                "content":"NASA and ESA (European Space Agency) have selected three astronauts to serve as crew members for NASA’s SpaceX Crew-3 mission to the International Space Station, which is expected to launch in the fall of 2021.",
                "img_path":"https://www.nasa.gov/sites/default/files/styles/full_width/public/thumbnails/image/crew-3_composite.png",
                "source_url":"www.nasa.gov",
            }

+ Response 202 (application/json)

    + Headers

            Location: /news/4

### Delete a specific news [DELETE]

You may delete an existing news using this action. It takes a JSON object containing the id of the news to delete.

+ Request (application/json)

    + Headers
    
            X-access-token: token

+ Response 200 (application/json)

    + Headers

            Location: /news/4

## Latest News [/api/v1/news/latest/{size}]

### Get the latest news [GET]

You may get the latest news using this action. You need to specify the number of how many news you want to be returned.

+ Response 200 (application/json)

            [
                {
                    "tags":["nasa","spacex"],
                    "_id":"5fd7a2e7f401d8460e80f3b4",
                    "date":"2020-12-14T17:37:43.558Z",
                    "title":"SXM-7 Mission",
                    "title_lowcase":"sxm-7 mission",
                    "content":"On Sunday, December 13 at 12:30 p.m. EST, Falcon 9 launched the SXM-7 mission from Space Launch Complex 40 (SLC-40) at Cape Canaveral Space Force Station, Florida",
                    "img_path":"https://www.nasaspaceflight.com/wp-content/uploads/2020/12/SXM-7-Falcon-9-B1051-LC-40-vertical-121020-SpaceX-1-scaled.jpg",
                    "source_url":"www.spacex.com",
                    "__v":0
                }
            ]
            
## Missions [/api/v1/missions]

### List all missions [GET]

+ Response 200 (application/json)

            [
                {
                    "img_path":["https://www.nasaspaceflight.com/wp-content/uploads/2020/12/SXM-7-Falcon-9-B1051-LC-40-vertical-121020-SpaceX-1-scaled.jpg"],
                    "tags":["spacex","nasa"],
                    "_id":"5fd78b1d8fcc26322f85a691",
                    "date":"2020-12-13T00:00:00.000Z",
                    "title":"SXM-7 Mission",
                    "title_lowcase":"sxm-7 mission",
                    "description":"On Sunday, December 13 at 12:30 p.m. EST, Falcon 9 launched the SXM-7 mission from Space Launch Complex 40 (SLC-40) at Cape Canaveral Space Force Station, Florida - SpaceX's 25th mission in 2020.",
                    "source_url":"www.spacex.com","__v":0
                },
                {
                    "img_path":["https://www.nasa.gov/sites/default/files/thumbnails/image/crew-1_ceitpt2-20200612-dsc05519_2_.jpg"],
                    "tags":["spacex","nasa"],
                    "_id":"5fd8a2e8fcfbb0661856332c",
                    "date":"2020-11-16T00:00:00.000Z",
                    "title":"CREW-1 MISSION",
                    "title_lowcase":"crew-1 mission",
                    "description":"On Monday, November 16 at 11:01 p.m. EST, 04:01 UTC on November 17, SpaceX’s Dragon autonomously docked with the International Space Station (ISS) after Falcon 9 launched the spacecraft to orbit from historic Launch Complex 39A (LC-39A) at NASA’s Kennedy Space Center in Florida on Sunday, November 15, 2020.",
                    "source_url":"www.spacex.com",
                    "__v":0
                }
            ]

### Add a new missions [POST]

You may add a new mission using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

    + Headers
    
            X-access-token: token
    
    + Body

            {
                "img_path":"https://www.nasa.gov/sites/default/files/thumbnails/image/crew-1_ceitpt2-20200612-dsc05519_2_.jpg",
                "tags":"spacex,nasa",
                "date":"2020-11-16T00:00:00.000Z",
                "title":"CREW-1 MISSION",
                "description":"On Monday, November 16 at 11:01 p.m. EST, 04:01 UTC on November 17, SpaceX’s Dragon autonomously docked with the International Space Station (ISS) after Falcon 9 launched the spacecraft to orbit from historic Launch Complex 39A (LC-39A) at NASA’s Kennedy Space Center in Florida on Sunday, November 15, 2020.",
                "source_url":"www.spacex.com"
            }

+ Response 201 (application/json)

    + Headers

            Location: /missions/2

## Specific Missions [/api/v1/missions/{id}]

### Get a specific mission [GET]

+ Response 201 (application/json)

        {
            "img_path":["https://www.nasaspaceflight.com/wp-content/uploads/2020/12/SXM-7-Falcon-9-B1051-LC-40-vertical-121020-SpaceX-1-scaled.jpg"],
            "tags":["spacex","nasa"],
            "_id":"5fd78b1d8fcc26322f85a691",
            "date":"2020-12-13T00:00:00.000Z",
            "title":"SXM-7 Mission",
            "title_lowcase":"sxm-7 mission",
            "description":"On Sunday, December 13 at 12:30 p.m. EST, Falcon 9 launched the SXM-7 mission from Space Launch Complex 40 (SLC-40) at Cape Canaveral Space Force Station, Florida - SpaceX's 25th mission in 2020.",
            "source_url":"www.spacex.com",
            "__v":0
        }

### Update a specific mission [PUT]

You may update an existing news using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

    + Headers
    
            X-access-token: token
    
    + Body

            {
                "img_path":"https://www.nasa.gov/sites/default/files/thumbnails/image/crew-1_ceitpt2-20200612-dsc05519_2_.jpg",
                "tags":"spacex,nasa",
                "date":"2020-11-16T00:00:00.000Z",
                "title":"CREW-1 MISSION",
                "description":"On Monday, November 16 at 11:01 p.m. EST, 04:01 UTC on November 17, SpaceX’s Dragon autonomously docked with the International Space Station (ISS) after Falcon 9 launched the spacecraft to orbit from historic Launch Complex 39A (LC-39A) at NASA’s Kennedy Space Center in Florida on Sunday, November 15, 2020.",
                "source_url":"www.spacex.com"
            }

+ Response 202 (application/json)

    + Headers

            Location: /missions/2

### Delete a specific mission [DELETE]

You may delete an existing mission using this action. It takes a JSON object containing the id of the mission to delete.

+ Request (application/json)

    + Headers
    
            X-access-token: token

+ Response 200 (application/json)

    + Headers

            Location: /missions/4

## Latest Missions [/api/v1/missions/latest/{size}]

### Get the latest mission [GET]

You may get the latest missions using this action. You need to specify the number of how many missions you want to be returned.

+ Response 200 (application/json)

            {
                "missions": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "CREW-1 MISSION",
                        "content": "n Monday, November 16 at 11:01 p.m. EST, 04:01 UTC on November 17, SpaceX’s Dragon autonomously docked with the International Space Station (ISS) after Falcon 9 launched the spacecraft to orbit from historic Launch Complex 39A (LC-39A) at NASA’s Kennedy Space Center in Florida on Sunday, November 15, 2020.",
                        "img": "",
                        "source": "https://www.spacex.com/updates/crew-1-docks-to-iss/index.html",
                        "tags": ["iss", "spacex", "nasa"],
                    }, {
                        "id": 2,
                        "date": "18/12/2019",
                        "title": "Cheops",
                        "content": " Characterising exoplanets known to be orbiting around nearby bright stars",
                        "img": ""
                        "source": "https://www.esa.int/Science_Exploration/Space_Science/Cheops",
                        "tags": ["esa", "exoplanets"],
                    }
                ]
            }
            
## Astronauts [/api/v1/astronauts]

### List all astronauts [GET]

+ Response 200 (application/json)

            [
                {
                    "img_path":["https://aerospacecue.it/wp-content/uploads/2020/01/Samantha_Cristoforetti_official_portrait_in_an_EMU_spacesuit.jpg"],
                    "tags":["esa"],
                    "_id":"5fd7923523272736a0888a4d",
                    "birth":"1977-04-26T00:00:00.000Z",
                    "name":"Samantha Cristoforetti",
                    "nationality":"ITA",
                    "agency":"ESA",
                    "__v":0
                },
                {
                    "img_path":["https://upload.wikimedia.org/wikipedia/commons/d/d8/Luca_Parmitano_EMU.jpg"],
                    "tags":["esa"],
                    "_id":"5fd792657392c030bcb21492",
                    "birth":"1976-09-27T00:00:00.000Z",
                    "name":"Luca Parmitano",
                    "nationality":"ITA",
                    "agency":"ESA",
                    "__v":0
                },
                {
                    "img_path":["https://upload.wikimedia.org/wikipedia/commons/6/60/Paolo_A._Nespoli_2016.jpg"],
                    "tags":["esa"],
                    "_id":"5fd792c97392c030bcb21493",
                    "birth":"1957-04-06T00:00:00.000Z",
                    "name":"Paolo Nespoli",
                    "nationality":"ITA",
                    "agency":"ESA",
                    "__v":0
                }
            ]

### Add a new astronaut [POST]

You may add a new astronaut using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

    + Headers
    
            X-access-token: token

    + Body

            {
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/6/60/Paolo_A._Nespoli_2016.jpg",
                "tags":"esa,nasa",
                "_id":"5fd792c97392c030bcb21493",
                "birth":"1957-04-06T00:00:00.000Z",
                "name":"Paolo Nespoli",
                "nationality":"ITA",
                "agency":"ESA"
            }

+ Response 201 (application/json)

    + Headers

            Location: /astroanuts/2
            

## Specific astronauts [/api/v1/astronauts/{id}]

### Get a specific astronaut [GET]

+ Response 200 (application/json)

            {
                "img_path":["https://aerospacecue.it/wp-content/uploads/2020/01/Samantha_Cristoforetti_official_portrait_in_an_EMU_spacesuit.jpg"],
                "tags":["esa"],
                "_id":"5fd7923523272736a0888a4d",
                "birth":"1977-04-26T00:00:00.000Z",
                "name":"Samantha Cristoforetti",
                "nationality":"ITA",
                "agency":"ESA",
                "__v":0
            }

### Update a specific astronaut [PUT]

You may update an existing astronaut using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

    + Headers
    
            X-access-token: token

    + Body

            {
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/6/60/Paolo_A._Nespoli_2016.jpg",
                "tags":"esa,nasa",
                "_id":"5fd792c97392c030bcb21493",
                "birth":"1957-04-06T00:00:00.000Z",
                "name":"Paolo Nespoli",
                "nationality":"ITA",
                "agency":"ESA"
            }

+ Response 202 (application/json)

    + Headers

            Location: /astronauts/1
            

### Delete a specific astronaut [DELETE]

You may delete an existing astronaut using this action. It takes a JSON object containing the id of the mission to delete.

+ Request (application/json)

    + Headers
    
            X-access-token: token

+ Response 200 (application/json)

    + Headers

            Location: /astronauts/4
            
## Telescopes [/api/v1/telescopes]

### List all telescopes [GET]

+ Response 200 (application/json)
            

                [
                    {
                        "img_path":["https://upload.wikimedia.org/wikipedia/commons/f/fd/Chandra_artist_illustration.jpg"],
                        "tags":["nasa","usa"],
                        "_id":"5fd7a6e53a4e2e4921a68acd",
                        "name":"Chandra X-ray Observatory",
                        "name_lowcase":"chandra x-ray observatory",
                        "description":"The Chandra X-ray Observatory (CXO), previously known as the Advanced X-ray Astrophysics Facility (AXAF), is a Flagship-class space telescope launched aboard the Space Shuttle Columbia during STS-93 by NASA on July 23, 1999. Chandra is sensitive to X-ray sources 100 times fainter than any previous X-ray telescope, enabled by the high angular resolution of its mirrors. Since the Earth's atmosphere absorbs the vast majority of X-rays, they are not detectable from Earth-based telescopes; therefore space-based telescopes are required to make these observations. Chandra is an Earth satellite in a 64-hour orbit, and its mission is ongoing as of 2020.",
                        "launch_date":"1999-07-03T00:00:00.000Z",
                        "source_url":"https://www.nasa.gov/",
                        "__v":0
                    },
                    {
                        "img_path":["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/CGRO_s37-96-010.jpg/1024px-CGRO_s37-96-010.jpg"],
                        "tags":["nasa","usa"],
                        "_id":"5fd8a83dfcfbb0661856332e",
                        "name":"Compton Gamma Ray Observatory",
                        "name_lowcase":"compton gamma ray observatory",
                        "description":"The Compton Gamma Ray Observatory (CGRO) was a space observatory detecting photons with energies from 20 keV to 30 GeV, in Earth orbit from 1991 to 2000. The observatory featured four main telescopes in one spacecraft, covering X-rays and gamma rays, including various specialized sub-instruments and detectors.",
                        "launch_date":"1991-04-05T00:00:00.000Z",
                        "source_url":"https://www.nasa.gov/",
                        "__v":0
                    }
                ]

### Add a new telescope [POST]

You may add a new telescope using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

    + Headers
    
            X-access-token: token

    + Body

            {
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/CGRO_s37-96-010.jpg/1024px-CGRO_s37-96-010.jpg",
                "tags":"nasa,usa",
                "name":"Compton Gamma Ray Observatory",
                "description":"The Compton Gamma Ray Observatory (CGRO) was a space observatory detecting photons with energies from 20 keV to 30 GeV, in Earth orbit from 1991 to 2000. The observatory featured four main telescopes in one spacecraft, covering X-rays and gamma rays, including various specialized sub-instruments and detectors.",
                "launch_date":"1991-04-05T00:00:00.000Z",
                "source_url":"https://www.nasa.gov/"
            }

+ Response 201 (application/json)

    + Headers

            Location: /telescopes/2

## Specific telescope [/api/v1/telescopes/{id}]

### Get a specific telescope [GET]

+ Response 200 (application/json)

        {
            "img_path":["https://upload.wikimedia.org/wikipedia/commons/f/fd/Chandra_artist_illustration.jpg"],
            "tags":["nasa","usa"],
            "_id":"5fd7a6e53a4e2e4921a68acd",
            "name":"Chandra X-ray Observatory",
            "name_lowcase":"chandra x-ray observatory",
            "description":"The Chandra X-ray Observatory (CXO), previously known as the Advanced X-ray Astrophysics Facility (AXAF), is a Flagship-class space telescope launched aboard the Space Shuttle Columbia during STS-93 by NASA on July 23, 1999. Chandra is sensitive to X-ray sources 100 times fainter than any previous X-ray telescope, enabled by the high angular resolution of its mirrors. Since the Earth's atmosphere absorbs the vast majority of X-rays, they are not detectable from Earth-based telescopes; therefore space-based telescopes are required to make these observations. Chandra is an Earth satellite in a 64-hour orbit, and its mission is ongoing as of 2020.",
            "launch_date":"1999-07-03T00:00:00.000Z",
            "source_url":"https://www.nasa.gov/",
            "__v":0
        }

### Update a specific telescope [PUT]

You may update an existing telescope using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

    + Headers
    
            X-access-token: token

    + Body

            {
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/CGRO_s37-96-010.jpg/1024px-CGRO_s37-96-010.jpg",
                "tags":"nasa,usa",
                "name":"Compton Gamma Ray Observatory",
                "description":"The Compton Gamma Ray Observatory (CGRO) was a space observatory detecting photons with energies from 20 keV to 30 GeV, in Earth orbit from 1991 to 2000. The observatory featured four main telescopes in one spacecraft, covering X-rays and gamma rays, including various specialized sub-instruments and detectors.",
                "launch_date":"1991-04-05T00:00:00.000Z",
                "source_url":"https://www.nasa.gov/"
            }

+ Response 202 (application/json)

    + Headers

            Location: /telescopes/2

### Delete a specific telescope [DELETE]

You may delete an existing telescope using this action. It takes a JSON object containing the id of the telescope to delete.

+ Request (application/json)

    + Headers
    
            X-access-token: token

+ Response 200 (application/json)

    + Headers

            Location: /telescopes/4

## Latest telescopes [/api/v1/telescopes/latest/{size}]

### Get the latest telescopes [GET]

You may get the latest telescopes using this action. You need to specify the number of how many telescopes you want to be returned.

+ Response 200 (application/json)

            [
                {
                    "img_path":["https://upload.wikimedia.org/wikipedia/commons/f/fd/Chandra_artist_illustration.jpg"],
                    "tags":["nasa","usa"],
                    "_id":"5fd7a6e53a4e2e4921a68acd",
                    "name":"Chandra X-ray Observatory",
                    "name_lowcase":"chandra x-ray observatory",
                    "description":"The Chandra X-ray Observatory (CXO), previously known as the Advanced X-ray Astrophysics Facility (AXAF), is a Flagship-class space telescope launched aboard the Space Shuttle Columbia during STS-93 by NASA on July 23, 1999. Chandra is sensitive to X-ray sources 100 times fainter than any previous X-ray telescope, enabled by the high angular resolution of its mirrors. Since the Earth's atmosphere absorbs the vast majority of X-rays, they are not detectable from Earth-based telescopes; therefore space-based telescopes are required to make these observations. Chandra is an Earth satellite in a 64-hour orbit, and its mission is ongoing as of 2020.",
                    "launch_date":"1999-07-03T00:00:00.000Z",
                    "source_url":"https://www.nasa.gov/",
                    "__v":0
                },
                {
                    "img_path":["https://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/CGRO_s37-96-010.jpg/1024px-CGRO_s37-96-010.jpg"],
                    "tags":["nasa","usa"],
                    "_id":"5fd8a83dfcfbb0661856332e",
                    "name":"Compton Gamma Ray Observatory",
                    "name_lowcase":"compton gamma ray observatory",
                    "description":"The Compton Gamma Ray Observatory (CGRO) was a space observatory detecting photons with energies from 20 keV to 30 GeV, in Earth orbit from 1991 to 2000. The observatory featured four main telescopes in one spacecraft, covering X-rays and gamma rays, including various specialized sub-instruments and detectors.",
                    "launch_date":"1991-04-05T00:00:00.000Z",
                    "source_url":"https://www.nasa.gov/",
                    "__v":0
                }
            ]
            
## Exoplanets [/api/v1/exoplanets]

### List all exoplanets [GET]

+ Response 200 (application/json)

        [
            {
                "tags":["nasa"],
                "_id":"5fd8a78752a46b07f76c031d",
                "discover_date":"1996-10-22T00:00:00.000Z",
                "name":"16 Cygni Bb",
                "name_lowcase":"16 cygni bb",
                "description":"16 Cygni Bb or HD 186427 b is an extrasolar planet approximately 69 light-years away in the constellation of Cygnus.",
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/6/65/16_Cygni_B_b.png",
                "source_url":"www.nasa.gov",
                "__v":0
            },
            {
                "tags":["nasa"],
                "_id":"5fd8aa9d6da89909aac9d600",
                "discover_date":"1996-01-17T23:00:00.000Z",
                "name":"70 Virginis b",
                "name_lowcase":"70 virginis b",
                "description":"70 Virginis b (abbreviated 70 Vir b) is an extrasolar planet approximately 60 light-years away in the constellation of Virgo.",
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/c/c0/70_virginis_b_%28Celestia%29.jpg",
                "source_url":"www.nasa.gov",
                "__v":0
            }
                    
        ]

### Add a new exoplanet [POST]

You may add a newly discovered exoplanet using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

    + Headers
    
            X-access-token: token

    + Body

            {
                "tags":"nasa,esa",
                "discover_date":"1996-01-17T23:00:00.000Z",
                "name":"70 Virginis b",
                "description":"70 Virginis b (abbreviated 70 Vir b) is an extrasolar planet approximately 60 light-years away in the constellation of Virgo.",
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/c/c0/70_virginis_b_%28Celestia%29.jpg",
                "source_url":"www.nasa.gov"
            }

+ Response 201 (application/json)

    + Headers

            Location: /exoplanets/2

## Specific exoplanet [/api/v1/exoplanets/{id}]

### Get a specific exoplanet [GET]

+ Response 200 (application/json)

        {
            "tags":["nasa"],
            "_id":"5fd8aa9d6da89909aac9d600",
            "discover_date":"1996-01-17T23:00:00.000Z",
            "name":"70 Virginis b",
            "name_lowcase":"70 virginis b",
            "description":"70 Virginis b (abbreviated 70 Vir b) is an extrasolar planet approximately 60 light-years away in the constellation of Virgo.",
            "img_path":"https://upload.wikimedia.org/wikipedia/commons/c/c0/70_virginis_b_%28Celestia%29.jpg",
            "source_url":"www.nasa.gov",
            "__v":0
        }

### Update a specific exoplanet [PUT]

You may update an existing exoplanet using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

    + Headers
    
            X-access-token: token

    + Body

            {
                "tags":"nasa,esa",
                "discover_date":"1996-01-17T23:00:00.000Z",
                "name":"70 Virginis b",
                "description":"70 Virginis b (abbreviated 70 Vir b) is an extrasolar planet approximately 60 light-years away in the constellation of Virgo.",
                "img_path":"https://upload.wikimedia.org/wikipedia/commons/c/c0/70_virginis_b_%28Celestia%29.jpg",
                "source_url":"www.nasa.gov"
            }

+ Response 202 (application/json)

    + Headers

            Location: /exoplanets/2

### Delete a specific exoplanet [DELETE]

You may delete an existing exoplanet using this action. It takes a JSON object containing the id of the telescope to delete.

+ Request (application/json)

    + Headers
    
            X-access-token: token

+ Response 200 (application/json)

    + Headers

            Location: /exoplanets/4

## Latest exoplanets [/api/v1/exoplanets/latest/{size}]

### Get the latest exoplanets [GET]

You may get the latest exoplanets using this action. You need to specify the number of how many exoplanets you want to be returned.

+ Response 200 (application/json)

            [
                {
                    "tags":["nasa"],
                    "_id":"5fd8aa9d6da89909aac9d600",
                    "discover_date":"1996-01-17T23:00:00.000Z",
                    "name":"70 Virginis b",
                    "name_lowcase":"70 virginis b",
                    "description":"70 Virginis b (abbreviated 70 Vir b) is an extrasolar planet approximately 60 light-years away in the constellation of Virgo.",
                    "img_path":"https://upload.wikimedia.org/wikipedia/commons/c/c0/70_virginis_b_%28Celestia%29.jpg",
                    "source_url":"www.nasa.gov",
                    "__v":0
                }, {
                    "tags":["nasa"],
                    "_id":"5fd8aa9d6da89909aac9d600",
                    "discover_date":"1996-01-17T23:00:00.000Z",
                    "name":"70 Virginis b",
                    "name_lowcase":"70 virginis b",
                    "description":"70 Virginis b (abbreviated 70 Vir b) is an extrasolar planet approximately 60 light-years away in the constellation of Virgo.",
                    "img_path":"https://upload.wikimedia.org/wikipedia/commons/c/c0/70_virginis_b_%28Celestia%29.jpg",
                    "source_url":"www.nasa.gov",
                    "__v":0
                }
            ]
            
## Creating an user account [/api/v1/signup]

### Sign up [POST]

You may sign up by providing a username and password. It takes a JSON object containing the necessary information.

+ Request (application/json)

            {
                "email": "user1",
                "password": "password",
            }

+ Response 201 (application/json)

    + Headers

            Location: /users/2
            
## Signing in [/api/v1/signin]
            
### Sign in [POST]

You may sign in to an existing user account by providing a username and password.

+ Request (application/json)

            {
                "email": "user2",
                "password": "password",
            }

+ Response 200 (application/json)

    + Headers

            Location: /users/2
            
## Get saved News [/api/v1/news/favourite]
            
### Get a saved article [GET]

If you're signed into your account, you may save an article to then read it later.

+ Request (application/json)

+ Response 202 (application/json)

    + Headers

            Location: /users/2
            
    + Body
    
            [
                {
                    "newsId":"5fd7a2e7f401d8460e80f3b4",
                    "userId":"jbndfbj34jhbjhb33334n3bnh",
                    "_id":"sdfkjbsdnkjbsnkbdjkjbksjh"
                },
                {
                    "newsId":"5fd7a2e7f401d8460e80f3b4",
                    "userId":"jbndfbj34jhbjhb33334n3bnh",
                    "_id":"sdfkjbsdnkjbsnkbdjkjbksjh"
                }
            ]
            
## Save News [/api/v1/news/favourite/{userId}]
            
### Save a specific article [POST]

If you're signed into your account, you may save an article to then read it later.

+ Request (application/json)

            {
                "userId": "unique ID",
                "newsid": "3",
            }

+ Response 202 (application/json)

    + Headers

            Location: /users/2
            
## Delete saved News [/api/v1/news/favourite/{userId}/{newsId}]
            
### Delete a specific article [DELETE]

If you're signed into your account, you may delete an article you saved previously.

+ Request (application/json)

+ Response 202 (application/json)

## Get followed Missions [/api/v1/missions/followed/{userId}]
            
### Follow a specific mission [GET]

If you're signed into your account, you may follow a specific mission to receive updates of it by name.

+ Request (application/json)

+ Response 202 (application/json)

    + Headers

            Location: /users/2
            
    + Body
    
            [
                {
                    "missionId":"5fd7a2e7f401d8460e80f3b4",
                    "userId":"jbndfbj34jhbjhb33334n3bnh",
                    "_id":"sdfkjbsdnkjbsnkbdjkjbksjh"
                },
                {
                    "missionId":"5fd7a2e7f401d8460e80f3b4",
                    "userId":"jbndfbj34jhbjhb33334n3bnh",
                    "_id":"sdfkjbsdnkjbsnkbdjkjbksjh"
                }
            ]

## Follow Missions [/api/v1/missions/followed]
            
### Follow a specific mission [POST]

If you're signed into your account, you may follow a specific mission to receive updates of it by name.

+ Request (application/json)

            {
                "userId": "unique ID",
                "missionId": "3",
            }

+ Response 202 (application/json)

    + Headers

            Location: /users/2
            
## Delete Followed Missions [/api/v1/missions/followed/{userId}/{missionId}]

### Unfollow a specific mission [DELETE]

If you're signed into your account, you unfollow a mission you followed earlier.

+ Request (application/json)


+ Response 202 (application/json)