FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# Laika API

Laika is an API service to return astronomy information and data. It can be used to obtain information about past and future space missions, astronauts, telescopes in function, newly discovered exoplanets and much more. Everything is returned in a standard JSON format.

## News [/news]

### List all news [GET]

+ Response 200 (application/json)

        [
            {
                "news": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
                        "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
                        "img": "",
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 2,
                        "date": "17/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Arrive at Space Station",
                        "content": " The SpaceX Crew Dragon Resilience successfully docked to the International Space Station at 11 p.m. EST Monday, transporting NASA astronauts Michael Hopkins, Victor Glover, Shannon Walker, and Japan Aerospace Exploration Agency (JAXA) astronaut Soichi Noguchi.",
                        "img": "https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw2046a.jpg"
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 3,
                        "date": "17/11/2020",
                        "title": "NASA Highlights Science, New Airlock on Space Station Resupply Mission",
                        "content": "NASA will host a media teleconference at 1 p.m. EST Friday, Nov. 20, to discuss science investigations and a new privately funded airlock launching on SpaceX’s 21st commercial cargo resupply mission for the agency to the International Space Station.",
                        "img": ""
                        "source": "https://www.nasa.gov",
                    }
                ]
            }
        ]

### Add a new news [POST]

You may add a new news using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

        {
            "date": "21/11/2020",
            "title": "Sea-level monitoring satellite in position for liftoff",
            "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
            "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
            "source": "https://www.esa.int",
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
                "date": "21/11/2020",
                "title": "Sea-level monitoring satellite in position for liftoff",
                "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
                "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
                "source": "https://www.esa.int",
            }

## Specific News [/news/{id}]

### Get a specific news [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "date": "16/11/2020",
            "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
            "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
            "img": "",
            "source": "https://www.nasa.gov",
        }

### Update a specific news [POST]

You may update an existing news using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 4,
            "date": "21/11/2020",
            "title": "Sea-level monitoring satellite in position for liftoff",
            "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
            "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
            "source": "https://www.esa.int",
        }

+ Response 202 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
                "date": "21/11/2020",
                "title": "Sea-level monitoring satellite in position for liftoff",
                "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
                "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
                "source": "https://www.esa.int",
            }

### Delete a specific news [DELETE]

You may delete an existing news using this action. It takes a JSON object containing the id of the news to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
            }

## Latest News [/news/{size}]

### Get the latest news [GET]

You may get the latest news using this action. You need to specify the number of how many news you want to be returned.

+ Response 200 (application/json)

        [
            {
                "news": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
                        "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
                        "img": "",
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 2,
                        "date": "17/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Arrive at Space Station",
                        "content": " The SpaceX Crew Dragon Resilience successfully docked to the International Space Station at 11 p.m. EST Monday, transporting NASA astronauts Michael Hopkins, Victor Glover, Shannon Walker, and Japan Aerospace Exploration Agency (JAXA) astronaut Soichi Noguchi.",
                        "img": "https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw2046a.jpg"
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 3,
                        "date": "17/11/2020",
                        "title": "NASA Highlights Science, New Airlock on Space Station Resupply Mission",
                        "content": "NASA will host a media teleconference at 1 p.m. EST Friday, Nov. 20, to discuss science investigations and a new privately funded airlock launching on SpaceX’s 21st commercial cargo resupply mission for the agency to the International Space Station.",
                        "img": ""
                        "source": "https://www.nasa.gov",
                    }
                ]
            }
        ]
## Missions [/missions]

### List all missions [GET]

+ Response 200 (application/json)

        [
            {
                "news": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
                        "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
                        "img": "",
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 2,
                        "date": "17/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Arrive at Space Station",
                        "content": " The SpaceX Crew Dragon Resilience successfully docked to the International Space Station at 11 p.m. EST Monday, transporting NASA astronauts Michael Hopkins, Victor Glover, Shannon Walker, and Japan Aerospace Exploration Agency (JAXA) astronaut Soichi Noguchi.",
                        "img": "https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw2046a.jpg"
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 3,
                        "date": "17/11/2020",
                        "title": "NASA Highlights Science, New Airlock on Space Station Resupply Mission",
                        "content": "NASA will host a media teleconference at 1 p.m. EST Friday, Nov. 20, to discuss science investigations and a new privately funded airlock launching on SpaceX’s 21st commercial cargo resupply mission for the agency to the International Space Station.",
                        "img": ""
                        "source": "https://www.nasa.gov",
                    }
                ]
            }
        ]

### Add a new missions [POST]

You may add a new news using this action. It takes a JSON object containing the necessary information.

+ Request (application/json)

        {
            "date": "21/11/2020",
            "title": "Sea-level monitoring satellite in position for liftoff",
            "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
            "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
            "source": "https://www.esa.int",
        }

+ Response 201 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
                "date": "21/11/2020",
                "title": "Sea-level monitoring satellite in position for liftoff",
                "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
                "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
                "source": "https://www.esa.int",
            }

## Specific Mission [/missions/{id}]

### Get a specific mission [GET]

+ Response 200 (application/json)

        {
            "id": 1,
            "date": "16/11/2020",
            "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
            "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
            "img": "",
            "source": "https://www.nasa.gov",
        }

### Update a specific mission [POST]

You may update an existing news using this action. It takes a JSON object containing the new complete information.

+ Request (application/json)

        {
            "id": 4,
            "date": "21/11/2020",
            "title": "Sea-level monitoring satellite in position for liftoff",
            "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
            "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
            "source": "https://www.esa.int",
        }

+ Response 202 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
                "date": "21/11/2020",
                "title": "Sea-level monitoring satellite in position for liftoff",
                "content": "With liftoff set for today at 17:17 GMT (18:17 CET, 09:17 PST), the Copernicus Sentinel-6 Michael Freilich satellite is poised for liftoff – atop a Falcon 9 rocket on the launch pad at the Vandenberg Air Force Base in California, US.",
                "img": "https://www.esa.int/var/esa/storage/images/esa_multimedia/images/2020/11/copernicus_sentinel-6_on_a_roll/22337310-2-eng-GB/Copernicus_Sentinel-6_on_a_roll_pillars.jpg"
                "source": "https://www.esa.int",
            }

### Delete a specific mission [DELETE]

You may delete an existing news using this action. It takes a JSON object containing the id of the news to delete.

+ Request (application/json)

        {
            "id": 4,
        }

+ Response 200 (application/json)

    + Headers

            Location: /questions/4

    + Body

            {
                "id": 4,
            }

## Latest Missions [/missions/{size}]

### Get the latest mission [GET]

You may get the latest news using this action. You need to specify the number of how many news you want to be returned.

+ Response 200 (application/json)

        [
            {
                "news": [
                    {
                        "id": 1,
                        "date": "16/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Headed to International Space Station",
                        "content": "An international crew of astronauts is en route to the International Space Station following a successful launch on the first NASA-certified commercial human spacecraft system in history. ",
                        "img": "",
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 2,
                        "date": "17/11/2020",
                        "title": "NASA’s SpaceX Crew-1 Astronauts Arrive at Space Station",
                        "content": " The SpaceX Crew Dragon Resilience successfully docked to the International Space Station at 11 p.m. EST Monday, transporting NASA astronauts Michael Hopkins, Victor Glover, Shannon Walker, and Japan Aerospace Exploration Agency (JAXA) astronaut Soichi Noguchi.",
                        "img": "https://www.nasa.gov/sites/default/files/styles/full_width_feature/public/thumbnails/image/potw2046a.jpg"
                        "source": "https://www.nasa.gov",
                    }, {
                        "id": 3,
                        "date": "17/11/2020",
                        "title": "NASA Highlights Science, New Airlock on Space Station Resupply Mission",
                        "content": "NASA will host a media teleconference at 1 p.m. EST Friday, Nov. 20, to discuss science investigations and a new privately funded airlock launching on SpaceX’s 21st commercial cargo resupply mission for the agency to the International Space Station.",
                        "img": ""
                        "source": "https://www.nasa.gov",
                    }
                ]
            }
        ]